import json
import logging
import os
import subprocess
import tempfile
import time
import uuid
from .helpers import Helpers as helpers
from novaclient import client as novaclient

class BuildFunctions(object):
    def __init__(self,
                 session,
                 region,
                 image_name,
                 avail_zone,
                 source_image,
                 ssh_user,
                 provision_script,
                 template_dir,
                 download_dir):
        self.session = session
        self.image_name = image_name
        self.avail_zone = avail_zone
        self.source_image = source_image
        self.ssh_user = ssh_user
        self.provision_script = provision_script
        self.template_dir = template_dir
        self.download_dir = download_dir
        self.tmp_dir = helpers.make_tmp_dir()
        self.nova = novaclient.Client("2", session=session, region_name=region)

    def cleanup(self, secgroup_id, keypair_id):
        """Cleans up the mess we've made"""
        logging.info('Removing temporary security group...')
        self.nova.security_groups.delete(group=secgroup_id)
        logging.info('Removing temporary keypair...')
        self.nova.keypairs.delete(key=keypair_id)

    def create_keypairs(self):
        """Creates a temporary keypair"""
        keyname = "imagebuilder-" + str(uuid.uuid4().hex)
        keypair = self.nova.keypairs.create(name=keyname)
        private_key = keypair.private_key
        '''We need to convert the generated RSA-key from BER to DER because of
        https://github.com/mitchellh/packer/issues/2526'''
        with tempfile.NamedTemporaryFile(delete=True) as temp:
            temp.write(bytes(private_key, 'ascii'))
            temp.flush()
            keypath = os.path.join(self.tmp_dir, 'packerKey')
            openssl_cmd = ['openssl', 'rsa', '-in', temp.name, '-out', keypath]
            process = subprocess.Popen(openssl_cmd,
                                       stdout=subprocess.PIPE,
                                       stderr=subprocess.STDOUT)
            process.wait()
            os.chmod(keypath, 0o600)
            #pylint: disable=logging-not-lazy
            logging.info("Saved private key in %s" % keypath)
        return keyname, keypair.id

    def create_security_group(self):
        """Creates a temporary security group"""
        secgroup_name = "imagebuilder-" + str(uuid.uuid4().hex)
        # pylint: disable=line-too-long
        secgroup = self.nova.security_groups.create(name=secgroup_name,
                                                    description='Temporary security group for image building')
        logging.info('Creating rule allowing SSH traffic...')
        self.nova.security_group_rules.create(secgroup.id,
                                              ip_protocol="tcp",
                                              from_port=22,
                                              to_port=22)
        return secgroup_name, secgroup.id

    def download_image(self, artifact_id):
        """Downloads image from Glance"""
        logging.info('Downloading image...')
        timestr = time.strftime("%Y%m%d")
        filename = self.image_name + timestr + '.raw'
        cmd = ['glance',
               'image-download',
               '--file', os.path.join(self.download_dir, filename),
               artifact_id]
        process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        with process.stdout:
            helpers.log_subprocess_output(process.stdout)
        exitcode = process.wait()
        return exitcode

    def parse_manifest(self):
        """Parses the manifest file generated by packer"""
        with open(os.path.join(self.tmp_dir, 'packer-manifest.json')) as data_file:
            manifest = json.load(data_file)
        artifact_id = manifest['builds'][0]['artifact_id']
        return artifact_id

    def run_packer(self, secgroup_name, key_name):
        """Executes Packer command"""
        image_name_var = 'image_name=' + self.image_name
        avail_zone_var = 'availability_zone=' + self.avail_zone
        secgroup_var = 'security_group=' + secgroup_name
        sshuser_var = 'ssh_username=' + self.ssh_user
        keyname_var = 'ssh_keypair_name=' + key_name
        keypath_var = 'ssh_key_path=' + os.path.join(self.tmp_dir, 'packerKey')
        source_image_var = 'source_image=' + self.source_image
        provision_script_var = 'provision_script=' + self.provision_script
        manifest_path_var = 'manifest_path=' + os.path.join(self.tmp_dir, 'packer-manifest.json')
        cmd = ['/usr/bin/packer', 'build',
               '-color=false',
               '--var', image_name_var,
               '--var', sshuser_var,
               '--var', secgroup_var,
               '--var', source_image_var,
               '--var', keyname_var,
               '--var', keypath_var,
               '--var', avail_zone_var,
               '--var', provision_script_var,
               '--var', manifest_path_var,
               os.path.join(self.template_dir, 'template')]
        logging.debug(cmd)
        process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        with process.stdout:
            helpers.log_subprocess_output(process.stdout)
        exitcode = process.wait()
        return exitcode
